package migration

// Entry pairs a Migration with the checksum used to detect later
// modifications. SQL migrations are checksummed from their file contents;
// Go migrations carry a checksum supplied at registration time (typically
// generated by `goforge generate` from the source file contents).
type Entry struct {
	Migration
	Checksum string
}
