package migration

import "fmt"

// Registry holds explicitly registered Go migrations. Go migration files are
// never parsed dynamically; they must call Register (directly, or through
// the file generated by `goforge generate`) to be picked up by the engine.
type Registry struct {
	entries map[uint64]Entry
}

// NewRegistry returns an empty Registry.
func NewRegistry() *Registry {
	return &Registry{entries: make(map[uint64]Entry)}
}

// Register adds a Go migration with the checksum computed at generation
// time from its source file. It returns ErrDuplicateVersion if the version
// was already registered.
func (r *Registry) Register(m Migration, checksum string) error {
	if _, exists := r.entries[m.Version()]; exists {
		return fmt.Errorf("%w: %d", ErrDuplicateVersion, m.Version())
	}
	r.entries[m.Version()] = Entry{Migration: m, Checksum: checksum}
	return nil
}

// All returns every registered entry, unordered.
func (r *Registry) All() []Entry {
	out := make([]Entry, 0, len(r.entries))
	for _, e := range r.entries {
		out = append(out, e)
	}
	return out
}
