// Package generator produces the explicit registry file for Go migrations,
// so that GoForge never has to parse or interpret .go migration files at
// runtime: `goforge generate` does the (static, source-level) discovery
// once, and the resulting file is plain Go the project compiles normally.
package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/MMaZX/goforge/migration"
)

// OutputFileName is the generated registry's fixed name, so `goforge
// generate` can find and overwrite it, and skip it when scanning for
// migration source files.
const OutputFileName = "goforge_registry_gen.go"

var goMigrationFileRE = regexp.MustCompile(`^(\d{6,})_(.+)\.go$`)

type discovered struct {
	version  uint64
	typeName string
	checksum string
}

// Generate scans dir for Go migration files named "000001_create_users.go"
// (the convention `goforge make:migration --go` produces, pairing a
// migration%06d type with its filename) and writes the registry file that
// registers each one with migration.Registry, checksummed from the file's
// contents at generation time.
func Generate(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("generator: reading %s: %w", dir, err)
	}

	var found []discovered
	seen := make(map[uint64]string)
	for _, e := range entries {
		if e.IsDir() || e.Name() == OutputFileName {
			continue
		}
		m := goMigrationFileRE.FindStringSubmatch(e.Name())
		if m == nil {
			continue
		}
		version, err := strconv.ParseUint(m[1], 10, 64)
		if err != nil {
			return fmt.Errorf("generator: invalid version in %q: %w", e.Name(), err)
		}
		if other, dup := seen[version]; dup {
			return fmt.Errorf("%w: %d (%q and %q)", migration.ErrDuplicateVersion, version, other, e.Name())
		}
		seen[version] = e.Name()

		content, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return fmt.Errorf("generator: reading %s: %w", e.Name(), err)
		}
		found = append(found, discovered{
			version:  version,
			typeName: fmt.Sprintf("migration%06d", version),
			checksum: migration.Checksum(content),
		})
	}

	sort.Slice(found, func(i, j int) bool { return found[i].version < found[j].version })

	return os.WriteFile(filepath.Join(dir, OutputFileName), []byte(render(found)), 0o644)
}

func render(found []discovered) string {
	var b strings.Builder
	b.WriteString("// Code generated by `goforge generate`. DO NOT EDIT.\n\n")
	b.WriteString("package migrations\n\n")
	b.WriteString("import \"github.com/MMaZX/goforge/migration\"\n\n")
	b.WriteString("// Registry returns every Go migration registered in this package.\n")
	b.WriteString("func Registry() (*migration.Registry, error) {\n")
	b.WriteString("\tr := migration.NewRegistry()\n")
	for _, d := range found {
		fmt.Fprintf(&b, "\tif err := r.Register(%s{}, %q); err != nil {\n\t\treturn nil, err\n\t}\n", d.typeName, d.checksum)
	}
	b.WriteString("\treturn r, nil\n")
	b.WriteString("}\n")
	return b.String()
}
